### ISSUE TITLE
Twitter Login Bug

### ISSUE THREAD

**Issue by fajita12** [fajita12/socialOctopus#19]

**Comment by RuiteGuo** [comment]
So the bug was originally resulted by our useage of twitter singleton function in twitter function to associate the consumer key and consumer secret. After I carefully read the documentation of the usage of twitter singleton, I realized that there is a description of "reusable". Associating with the error we keep getting which is "Consumer key/token pair already set", I think reusable is responsible for this bug. So I corrected it with normal usage of creating a twitter object.

**Comment by pncklypear** [comment]
Resolved
